name: ObserverPaper
version: "1.0.1"
main: com.observer.paper.ObserverPaper
api-version: "1.21"
authors: [Pumpkings]
description: Server-side component of the Observer architecture.
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
